name: build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install frontend dependencies
        run: cd ui && npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}