name: create release

on:
  workflow_dispatch:
    inputs:
      releaseName:
        required: true
        type: string
        description: Title of the release, generally the version number

jobs:
  release:
    name: draft release
    uses: ./.github/workflows/build.yml
    with:
      buildOnly: false
      prerelease: ${{ github.event_name == 'prerelease' }}
      releaseName: ${{ inputs.releaseName }}