name: release

on:
  workflow_dispatch:
  release:
    types:
      - prereleased
      - released

jobs:
  build:
    name: build packages
    uses: ./.github/workflows/build.yml
    with:
      artifactName: release-bundle
  upload:
    name: upload binaries
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - name: download binaries
        uses: actions/download-artifact@v3
        with:
          name: release-bundle