name: package release

on:
  workflow_dispatch:
  release:
    types:
      - prereleased
      - released

jobs:
  build:
    name: build packages
    uses: ./.github/workflows/build.yml

  upload:
    name: upload binaries
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3

      - name: download binaries
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts
      - run: ls -a
      - name: upload to github release
        run: gh release upload ${{ github.ref_name }} chats-controller_0.2.2_x64_en-US.msi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

