name: create release

on:
  workflow_dispatch:

jobs:
  build:
    name: build and publish release
    uses: ./.github/workflows/build.yml
    with:
      buildOnly: false
      prerelease: ${{ github.event_name == 'prerelease' }}