name: create release

on:
  workflow_dispatch:
    inputs:
      releaseName:
        required: true
        type: string
        description: Title of the release, generally the version number
      prerelease:
        required: false
        type: boolean
        description: Whether or not to mark the release as a pre-release
        default: true

jobs:
  release:
    name: draft release
    uses: ./.github/workflows/build.yml
    with:
      buildOnly: false
      prerelease: ${{ inputs.prerelease }}
      releaseName: ${{ inputs.releaseName }}